/**
 * Ideas Gallery Data
 *
 * Auto-generated by scripts/sync-ideas.mjs
 * DO NOT EDIT MANUALLY - Run "npm run ideas:sync" to update
 *
 * Last updated: 2026-01-02T05:35:38.645Z
 */

export interface Idea {
  id: string;
  title: string;
  category: string;
  tags: string[];
  src: string;
}

export const ideas: Idea[] = [
  {
    id: 'idea-1767332138271-j51hnji7v',
    title: '2',
    category: 'Relationships',
    tags: ['Relationships'],
    src: '/ideas/relationship-2.jpg',
  },
  {
    id: 'idea-1767332138292-otas2fftj',
    title: '3',
    category: 'Relationships',
    tags: ['Relationships'],
    src: '/ideas/relationship-3.jpg',
  },
  {
    id: 'idea-1767332138313-ij8egkweg',
    title: '2',
    category: 'Money',
    tags: ['Money', 'Finance'],
    src: '/ideas/money-2.jpg',
  },
  {
    id: 'idea-1767332138334-nmkbeyt69',
    title: '1',
    category: 'Money',
    tags: ['Money', 'Finance'],
    src: '/ideas/money-1.jpg',
  },
  {
    id: 'idea-1767332138345-hhhrtf4l4',
    title: '3',
    category: 'Career',
    tags: ['Career'],
    src: '/ideas/career-3.jpg',
  },
  {
    id: 'idea-1767332138363-c0187toz8',
    title: '2',
    category: 'Career',
    tags: ['Career'],
    src: '/ideas/career-2.jpg',
  },
  {
    id: 'idea-1767332138409-hkm4kt19d',
    title: '1',
    category: 'Career',
    tags: ['Career'],
    src: '/ideas/career-1.jpg',
  },
  {
    id: 'idea-1767332138423-3s8wzwcfo',
    title: '3',
    category: 'Health',
    tags: ['Health'],
    src: '/ideas/health-3.jpg',
  },
  {
    id: 'idea-1767332138444-bsal1lvsw',
    title: '3',
    category: 'Travel',
    tags: ['Travel'],
    src: '/ideas/travel-3.jpg',
  },
  {
    id: 'idea-1767332138466-ia2shjus1',
    title: '2',
    category: 'Travel',
    tags: ['Travel'],
    src: '/ideas/travel-2.jpg',
  },
  {
    id: 'idea-1767332138490-3ffj6j10n',
    title: '1',
    category: 'Travel',
    tags: ['Travel'],
    src: '/ideas/travel-1.jpg',
  },
  {
    id: 'idea-1767332138510-rzeembghq',
    title: '3',
    category: 'Study',
    tags: ['Study', 'Learning'],
    src: '/ideas/study-3.jpg',
  },
  {
    id: 'idea-1767332138527-63xthf18u',
    title: '2',
    category: 'Study',
    tags: ['Study', 'Learning'],
    src: '/ideas/study-2.jpg',
  },
  {
    id: 'idea-1767332138544-8amh2qe5w',
    title: '1',
    category: 'Study',
    tags: ['Study', 'Learning'],
    src: '/ideas/study-1.jpg',
  },
  {
    id: 'idea-1767332138564-woyjl99ap',
    title: '1',
    category: 'Relationships',
    tags: ['Relationships'],
    src: '/ideas/relationship-1.jpg',
  },
  {
    id: 'idea-1767332138589-yppf5qj0n',
    title: '2',
    category: 'Health',
    tags: ['Health'],
    src: '/ideas/health-2.jpg',
  },
  {
    id: 'idea-1767332138608-kezinv6vj',
    title: '1',
    category: 'Health',
    tags: ['Health'],
    src: '/ideas/health-1.jpg',
  },
  {
    id: 'idea-1767332138631-w9glucij5',
    title: '3',
    category: 'Money',
    tags: ['Money', 'Finance'],
    src: '/ideas/money-3.jpg',
  }
];

// Export categories for filtering
export const categories = [
  'All',
  'Career',
  'Money',
  'Health',
  'Relationships',
  'Study',
  'Travel',
  'General',
] as const;

export type Category = typeof categories[number];
